# This file is part of BenchExec, a framework for reliable benchmarking:
# https://github.com/sosy-lab/benchexec
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

language: python
sudo: required
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install .
  # Install code formatter black, but only on versions where it is available
  - pip install black || true
before_script:
  - sudo ./.travis-setup.sh "$USER"
  # Disable one specific test that often fails on Travis.
  # This is due to a deadlock in the Python interpreter or used libraries
  # and there is nothing we can do. Luckily on new Python it does not occur.
  - sed -i benchexec/test_integration/__init__.py -e '/test_simple_parallel/ i \    @unittest.skipIf(sys.version_info < (3,7), "Fails nondeterministically if load is high")'
script:
  - python setup.py test
  # Revert local modification before checking source format
  - git checkout .
  - if which black; then black . --check --diff; fi
notifications:
  email:
    - benchexec-dev@googlegroups.com
